## Tutorial 09 Python pandas tutorials part 2

in part we are going to learn about 
1. StringIo
2. pandas read_cvs

In [74]:
### reading Different data sourceswith the of pandas
from io import StringIO
import requests

In [75]:
import pandas as pd
df=pd.read_csv('hotel_bookings.csv')
df.head()

   is_canceled  lead_time  arrival_date_year
0            0        342               2015
1            0        737               2015
2            0          7               2015
3            0         13               2015
4            0         14               2015

In [76]:
type(df)

pandas.core.frame.DataFrame

In [77]:
data = ('col1,col2,col3\n'
       'x,y,1\n'
       'a,b,2\n'
       'c,d,3')

In [78]:
type(data)

str

In [79]:
## in memeory  file format oblect
StringIO(data)

In [80]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [81]:
pd.read_csv(StringIO(data),usecols=['col1','col2'])

  col1 col2
0    x    y
1    a    b
2    c    d

In [82]:
import pandas as pd
df=pd.read_csv('hotel_bookings.csv')
df.head()

   is_canceled  lead_time  arrival_date_year
0            0        342               2015
1            0        737               2015
2            0          7               2015
3            0         13               2015
4            0         14               2015

In [83]:
df=pd.read_csv('hotel_bookings.csv',usecols=['is_canceled','lead_time','arrival_date_year'])
df.head()

   is_canceled  lead_time  arrival_date_year
0            0        342               2015
1            0        737               2015
2            0          7               2015
3            0         13               2015
4            0         14               2015

In [84]:
df.to_csv('hotel_bookings.csv',index=False)
df.head()

   is_canceled  lead_time  arrival_date_year
0            0        342               2015
1            0        737               2015
2            0          7               2015
3            0         13               2015
4            0         14               2015

In [85]:
## datatypes in csv
data1 = ('a,b,c,d\n'
       '1,2,3,4\n'
       '5,6,7,8\n'
       '9,10,11')

In [86]:
pd.read_csv(StringIO(data1))

   a   b   c    d
0  1   2   3  4.0
1  5   6   7  8.0
2  9  10  11  NaN

In [87]:
df = pd.read_csv(StringIO(data1),dtype='object')

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      object
 1   b       3 non-null      object
 2   c       3 non-null      object
 3   d       2 non-null      object
dtypes: object(4)
memory usage: 228.0+ bytes

In [89]:
df.head()

   a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN

In [90]:
df.isnull().sum()

a    0
b    0
c    0
d    1
dtype: int64

In [91]:
df['a'][0]

'1'

In [92]:
## datatypes in csv
data1 = ('a,b,c,d\n'
       '1,2,3,4\n'
       '5,6,7,8\n'
       '9,10,11')

In [93]:
df=pd.read_csv(StringIO(data1),dtype={'a':int,'b':float,'c':int})

In [94]:
df

   a     b   c    d
0  1   2.0   3  4.0
1  5   6.0   7  8.0
2  9  10.0  11  NaN

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      float64
 2   c       3 non-null      int64
 3   d       2 non-null      float64
dtypes: float64(2), int64(2)
memory usage: 228.0 bytes

In [96]:
df.dtypes

a      int64
b    float64
c      int64
d    float64
dtype: object

In [97]:
data2 = ('index,a,b,c\n'
        '4,apple,bat,5.7\n'
        '8,orange,cow,10')

In [98]:
pd.read_csv(StringIO(data2),index_col=0)

            a    b     c
index
4       apple  bat   5.7
8      orange  cow  10.0

In [99]:
## use index clos and usecols
data2 = ('index,a,b,c\n'
        '4,apple,bat,5.7\n'
        '8,orange,cow,')

In [100]:
pd.read_csv(StringIO(data2),usecols=['a','b','c'],index_col=0)

          b    c
a
apple   bat  5.7
orange  cow  NaN

In [108]:
pd.read_csv('cu (1).item',sep='\t')

,item_code,item_name,display_level,selectable,sort_sequence
0,AA0,All items - old base,0,T,2
1,AA0R,Purchasing power of the consumer dollar - old ...,0,T,400
2,SA0,All items,0,T,1
3,SA0E,Energy,1,T,375
4,SA0L1,All items less food,1,T,359
...,...,...,...,...,...
395,SSEA011,College textbooks,3,T,314
396,SSEE041,Smartphones,4,T,335
397,SSFV031A,Food at elementary and secondary schools,3,T,122
398,SSGE013,Infants' equipment,3,T,356
399,SSHJ031,Infants' furniture,3,T,165