In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
#

In [63]:
df = pd.read_csv('/content/drive/MyDrive/Data  Set/adult.csv')

In [64]:
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [65]:
df.shape

(32561, 15)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [67]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [68]:
df['income'].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [69]:
df = pd.get_dummies(
    df,
    columns=[
        'workclass',
        'education',
        'marital.status',
        'occupation',
        'relationship',
        'race',
        'sex',
        'native.country'
    ],
    drop_first=True
)

In [70]:
df['income'] = df['income'].map({'<=50K':0,'>50K':1})

In [71]:
df['income'].value_counts()

income
0    24720
1     7841
Name: count, dtype: int64

In [72]:
df.columns

Index(['age', 'fnlwgt', 'education.num', 'capital.gain', 'capital.loss',
       'hours.per.week', 'income', 'workclass_Federal-gov',
       'workclass_Local-gov', 'workclass_Never-worked',
       ...
       'native.country_Portugal', 'native.country_Puerto-Rico',
       'native.country_Scotland', 'native.country_South',
       'native.country_Taiwan', 'native.country_Thailand',
       'native.country_Trinadad&Tobago', 'native.country_United-States',
       'native.country_Vietnam', 'native.country_Yugoslavia'],
      dtype='object', length=101)

In [73]:
x = df.drop('income', axis=1)
y = df['income']

In [74]:
x.head()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,workclass_Private,...,native.country_Portugal,native.country_Puerto-Rico,native.country_Scotland,native.country_South,native.country_Taiwan,native.country_Thailand,native.country_Trinadad&Tobago,native.country_United-States,native.country_Vietnam,native.country_Yugoslavia
0,90,77053,9,0,4356,40,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,82,132870,9,0,4356,18,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2,66,186061,10,0,4356,40,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,54,140359,4,0,3900,40,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
4,41,264663,10,0,3900,40,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False

In [75]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: income, dtype: int64

In [77]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [78]:
from sklearn.linear_model import LogisticRegression

In [79]:
model = LogisticRegression()

In [80]:
model.fit(x_train,y_train)

LogisticRegression()

In [90]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [91]:
from  sklearn.metrics import accuracy_score, confusion_matrix, classification_report,precision_score,recall_score,f1_score

In [92]:
print('Train Confusion Matrix :-\n',confusion_matrix(y_train,train_pred))
print('Train Accuracy :-',accuracy_score(y_train,train_pred))
print('Train Precision :-',precision_score(y_train,train_pred))
print('Train Recall :-',recall_score(y_train,train_pred))

Train Confusion Matrix :-
 [[19109   635]
 [ 4665  1639]]
Train Accuracy :- 0.796529484029484
Train Precision :- 0.7207563764291997
Train Recall :- 0.25999365482233505

In [93]:
print('Test Confusion Matrix :-\n',confusion_matrix(y_test,test_pred))
print('Test Accuracy :-',accuracy_score(y_test,test_pred))
print('Test Precision :-',precision_score(y_test,test_pred))
print('Test Recall :-',recall_score(y_test,test_pred))

Test Confusion Matrix :-
 [[4815  161]
 [1161  376]]
Test Accuracy :- 0.7970213419315215
Test Precision :- 0.7001862197392924
Test Recall :- 0.2446324007807417

** DecisionTreeClassifier **

In [95]:
from sklearn.tree import DecisionTreeClassifier

In [96]:
model = DecisionTreeClassifier()

In [97]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [98]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [99]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,precision_score,recall_score,f1_score

In [100]:
print('Train Confusion Matrix :-\n',confusion_matrix(y_train,train_pred))
print('Train Accuracy :-',accuracy_score(y_train,train_pred))
print('Train Precision :-',precision_score(y_train,train_pred))
print('Train Recall :-',recall_score(y_train,train_pred))

Train Confusion Matrix :-
 [[19744     0]
 [    1  6303]]
Train Accuracy :- 0.9999616093366094
Train Precision :- 1.0
Train Recall :- 0.9998413705583756

In [101]:
print('Test Confusion Matrix :-\n',confusion_matrix(y_test,test_pred))
print('Test Accuracy :-',accuracy_score(y_test,test_pred))
print('Test Precision :-',precision_score(y_test,test_pred))
print('Test Recall :-',recall_score(y_test,test_pred))

Test Confusion Matrix :-
 [[4357  619]
 [ 594  943]]
Test Accuracy :- 0.8137571011822509
Test Precision :- 0.6037131882202305
Test Recall :- 0.6135328562134027

## RandomForestClassifre

In [102]:
from sklearn.ensemble import RandomForestClassifier

In [103]:
model = RandomForestClassifier()

In [104]:
model.fit(x_train,y_train)

RandomForestClassifier()

In [113]:

print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19744
           1       1.00      1.00      1.00      6304

    accuracy                           1.00     26048
   macro avg       1.00      1.00      1.00     26048
weighted avg       1.00      1.00      1.00     26048

In [114]:

print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.88      0.88      0.88      4976
           1       0.60      0.61      0.61      1537

    accuracy                           0.81      6513
   macro avg       0.74      0.74      0.74      6513
weighted avg       0.81      0.81      0.81      6513

In [105]:
print('Train Confusion Matrix :-\n',confusion_matrix(y_train,train_pred))
print('Train Accuracy :-',accuracy_score(y_train,train_pred))
print('Train Precision :-',precision_score(y_train,train_pred))
print('Train Recall :-',recall_score(y_train,train_pred))

Train Confusion Matrix :-
 [[19744     0]
 [    1  6303]]
Train Accuracy :- 0.9999616093366094
Train Precision :- 1.0
Train Recall :- 0.9998413705583756

In [106]:
print('Test Confusion Matrix :-\n',confusion_matrix(y_test,test_pred))
print('Test Accuracy :-',accuracy_score(y_test,test_pred))
print('Test Precision :-',precision_score(y_test,test_pred))
print('Test Recall :-',recall_score(y_test,test_pred))

Test Confusion Matrix :-
 [[4357  619]
 [ 594  943]]
Test Accuracy :- 0.8137571011822509
Test Precision :- 0.6037131882202305
Test Recall :- 0.6135328562134027

## GradientBoostingClassifier

In [117]:
from sklearn.ensemble import GradientBoostingClassifier

In [118]:
model = GradientBoostingClassifier()

In [119]:
model.fit(x_train,y_train)

GradientBoostingClassifier()

In [120]:

print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19744
           1       1.00      1.00      1.00      6304

    accuracy                           1.00     26048
   macro avg       1.00      1.00      1.00     26048
weighted avg       1.00      1.00      1.00     26048

In [121]:

print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.88      0.88      0.88      4976
           1       0.60      0.61      0.61      1537

    accuracy                           0.81      6513
   macro avg       0.74      0.74      0.74      6513
weighted avg       0.81      0.81      0.81      6513

## GridSearchCV

In [136]:
from sklearn.model_selection import GridSearchCV

In [138]:
param_grid = {
    'n_estimators': [100, 200],
    'learning_rate': [0.05, 0.1],
    'max_depth': [3, 5]
}
model = GridSearchCV(estimator=GradientBoostingClassifier(), param_grid=param_grid, cv=3, verbose=2, n_jobs=-1)

In [139]:
model = GradientBoostingClassifier()

In [140]:
model.fit(x_train,y_train)

GradientBoostingClassifier()

In [141]:
print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19744
           1       1.00      1.00      1.00      6304

    accuracy                           1.00     26048
   macro avg       1.00      1.00      1.00     26048
weighted avg       1.00      1.00      1.00     26048

In [144]:
confusion_matrix(y_train,train_pred)

array([[19744,     0],
       [    1,  6303]])

In [143]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.88      0.88      0.88      4976
           1       0.60      0.61      0.61      1537

    accuracy                           0.81      6513
   macro avg       0.74      0.74      0.74      6513
weighted avg       0.81      0.81      0.81      6513

In [145]:
confusion_matrix(y_test,test_pred)

array([[4357,  619],
       [ 594,  943]])

## GaussianNB

In [146]:
from sklearn.naive_bayes import GaussianNB

In [147]:
mdel = GaussianNB()

In [148]:
model.fit(x_train,y_train)

GradientBoostingClassifier()

In [149]:
print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19744
           1       1.00      1.00      1.00      6304

    accuracy                           1.00     26048
   macro avg       1.00      1.00      1.00     26048
weighted avg       1.00      1.00      1.00     26048

In [150]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.88      0.88      0.88      4976
           1       0.60      0.61      0.61      1537

    accuracy                           0.81      6513
   macro avg       0.74      0.74      0.74      6513
weighted avg       0.81      0.81      0.81      6513

In [151]:
from sklearn.neighbors import KNeighborsRegressor

In [152]:
model = KNeighborsRegressor()

In [153]:
model.fit(x_train,y_train)

KNeighborsRegressor()

In [154]:
print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19744
           1       1.00      1.00      1.00      6304

    accuracy                           1.00     26048
   macro avg       1.00      1.00      1.00     26048
weighted avg       1.00      1.00      1.00     26048

In [156]:
confusion_matrix(y_train,train_pred)

array([[19744,     0],
       [    1,  6303]])

In [155]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.88      0.88      0.88      4976
           1       0.60      0.61      0.61      1537

    accuracy                           0.81      6513
   macro avg       0.74      0.74      0.74      6513
weighted avg       0.81      0.81      0.81      6513

In [157]:
confusion_matrix(y_test,test_pred)

array([[4357,  619],
       [ 594,  943]])